### ISSUE TITLE
bug: Rvx Builder Patching Bug for v2.220.2

### ISSUE THREAD

**Issue by ezeraiser** [YT-Advanced/ReX-patches#45]
### Bug description

When i use rvx-builder-win.exe download everthing is good. Then starting patch is getting error.

### Error logs

```shell
[builder] INFO: Loading patches
[builder] java.io.FileNotFoundException: C:\xxx\revanced (Access denied) at java.base/java.io.RandomAccessFile.open0(Native Method) at java.base/java.io.RandomAccessFile.open(Unknown Source) at java.base/java.io.RandomAccessFile.(Unknown Source) at java.base/java.io.RandomAccessFile.(Unknown Source) at java.base/java.util.zip.ZipFile$Source.(Unknown Source) at java.base/java.util.zip.ZipFile$Source.get(Unknown Source) at java.base/java.util.zip.ZipFile$CleanableResource.(Unknown Source) at java.base/java.util.zip.ZipFile.(Unknown Source) at java.base/java.util.zip.ZipFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at java.base/java.util.jar.JarFile.(Unknown Source) at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:106) at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:105) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt:140) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt) at app.revanced.patcher.PatchBundleLoader.(PatchBundleLoader.kt:34) at app.revanced.patcher.PatchBundleLoader$Jar.(PatchBundleLoader.kt:102) at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:259) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by YT-Advanced** [comment]
I think rvx-builder is almost died 🫠
